# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_CNUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWnd(object):
    def setupUi(self, MainWnd):
        MainWnd.setObjectName("MainWnd")
        MainWnd.resize(1080, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWnd.setWindowIcon(icon)
        MainWnd.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWnd)
        self.centralwidget.setObjectName("centralwidget")
        self.Work_Area = QtWidgets.QTabWidget(self.centralwidget)
        self.Work_Area.setGeometry(QtCore.QRect(0, 0, 1080, 761))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 15, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        self.Work_Area.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Work_Area.setFont(font)
        self.Work_Area.setObjectName("Work_Area")
        self.TAB_Debug = QtWidgets.QWidget()
        self.TAB_Debug.setObjectName("TAB_Debug")
        self.DEBUG_Pages = QtWidgets.QTabWidget(self.TAB_Debug)
        self.DEBUG_Pages.setGeometry(QtCore.QRect(-2, -2, 1081, 744))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.DEBUG_Pages.setFont(font)
        self.DEBUG_Pages.setObjectName("DEBUG_Pages")
        self.TAB_terminal = QtWidgets.QWidget()
        self.TAB_terminal.setObjectName("TAB_terminal")
        self.CMD = QtWidgets.QListWidget(self.TAB_terminal)
        self.CMD.setGeometry(QtCore.QRect(0, 0, 894, 672))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 9, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 9, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 181, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.CMD.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Inziu IosevkaCC Slab CL")
        font.setPointSize(11)
        self.CMD.setFont(font)
        self.CMD.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.CMD.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.CMD.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.CMD.setModelColumn(0)
        self.CMD.setBatchSize(64)
        self.CMD.setSelectionRectVisible(True)
        self.CMD.setObjectName("CMD")
        self.frame_2 = QtWidgets.QFrame(self.TAB_terminal)
        self.frame_2.setGeometry(QtCore.QRect(0, 671, 894, 48))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.CMD_B = QtWidgets.QLabel(self.frame_2)
        self.CMD_B.setGeometry(QtCore.QRect(0, 0, 894, 48))
        self.CMD_B.setStyleSheet("border-image: url(:/Res/Terminal_B.jpg);")
        self.CMD_B.setObjectName("CMD_B")
        self.CMD_Line = QtWidgets.QLineEdit(self.frame_2)
        self.CMD_Line.setGeometry(QtCore.QRect(50, 4, 721, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.CMD_Line.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Inziu IosevkaCC Slab SC")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.CMD_Line.setFont(font)
        self.CMD_Line.setText("")
        self.CMD_Line.setObjectName("CMD_Line")
        self.CMD_Clear = QtWidgets.QPushButton(self.frame_2)
        self.CMD_Clear.setGeometry(QtCore.QRect(785, 7, 26, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CMD_Clear.setFont(font)
        self.CMD_Clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CMD_Clear.setStyleSheet("border-image: url(:/Res/Clear.png);")
        self.CMD_Clear.setObjectName("CMD_Clear")
        self.CMD_Stop = QtWidgets.QPushButton(self.frame_2)
        self.CMD_Stop.setGeometry(QtCore.QRect(821, 7, 26, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CMD_Stop.setFont(font)
        self.CMD_Stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CMD_Stop.setStyleSheet("border-image: url(:/Res/Stop.png);")
        self.CMD_Stop.setObjectName("CMD_Stop")
        self.CMD_Add = QtWidgets.QPushButton(self.frame_2)
        self.CMD_Add.setGeometry(QtCore.QRect(857, 7, 26, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CMD_Add.setFont(font)
        self.CMD_Add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CMD_Add.setStyleSheet("border-image: url(:/Res/Stop.png);\n"
"border-image: url(:/Res/Add.png);")
        self.CMD_Add.setObjectName("CMD_Add")
        self.Q_comm = QtWidgets.QListWidget(self.TAB_terminal)
        self.Q_comm.setGeometry(QtCore.QRect(895, 37, 180, 678))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 235, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Q_comm.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Computer Modern")
        font.setPointSize(11)
        self.Q_comm.setFont(font)
        self.Q_comm.setObjectName("Q_comm")
        self.widget_2 = QtWidgets.QWidget(self.TAB_terminal)
        self.widget_2.setGeometry(QtCore.QRect(894, 0, 180, 38))
        self.widget_2.setStyleSheet("border-image: url(:/Res/QCommT.jpg);")
        self.widget_2.setObjectName("widget_2")
        self.CMD2DB = QtWidgets.QWidget(self.TAB_terminal)
        self.CMD2DB.setGeometry(QtCore.QRect(582, 304, 312, 366))
        self.CMD2DB.setStyleSheet("")
        self.CMD2DB.setObjectName("CMD2DB")
        self.CMD2DB_B = QtWidgets.QLabel(self.CMD2DB)
        self.CMD2DB_B.setGeometry(QtCore.QRect(0, 0, 312, 120))
        self.CMD2DB_B.setStyleSheet("border-image: url(:/Res/CMD2Data_B.png);")
        self.CMD2DB_B.setText("")
        self.CMD2DB_B.setObjectName("CMD2DB_B")
        self.CMD2DB_VIEW = QtWidgets.QPushButton(self.CMD2DB)
        self.CMD2DB_VIEW.setGeometry(QtCore.QRect(20, 81, 36, 36))
        self.CMD2DB_VIEW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CMD2DB_VIEW.setStyleSheet("border-image: url(:/Res/CMD2DB_VIEW.png);")
        self.CMD2DB_VIEW.setText("")
        self.CMD2DB_VIEW.setObjectName("CMD2DB_VIEW")
        self.CMD2DB_OK = QtWidgets.QPushButton(self.CMD2DB)
        self.CMD2DB_OK.setGeometry(QtCore.QRect(139, 85, 36, 36))
        self.CMD2DB_OK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CMD2DB_OK.setStyleSheet("border-image: url(:/Res/CMD2DB_OK.png);")
        self.CMD2DB_OK.setText("")
        self.CMD2DB_OK.setObjectName("CMD2DB_OK")
        self.CMD2DB_NO = QtWidgets.QPushButton(self.CMD2DB)
        self.CMD2DB_NO.setGeometry(QtCore.QRect(252, 81, 36, 36))
        self.CMD2DB_NO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CMD2DB_NO.setStyleSheet("border-image: url(:/Res/CMD2DB_NO.png);")
        self.CMD2DB_NO.setText("")
        self.CMD2DB_NO.setObjectName("CMD2DB_NO")
        self.CMD2DB_DRAG = QtWidgets.QPushButton(self.CMD2DB)
        self.CMD2DB_DRAG.setGeometry(QtCore.QRect(280, 0, 28, 28))
        self.CMD2DB_DRAG.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.CMD2DB_DRAG.setStyleSheet("border-image: url(:/Res/CMD2DB_DRAG.png);")
        self.CMD2DB_DRAG.setText("")
        self.CMD2DB_DRAG.setObjectName("CMD2DB_DRAG")
        self.CMD2DB_line = QtWidgets.QLineEdit(self.CMD2DB)
        self.CMD2DB_line.setGeometry(QtCore.QRect(26, 48, 256, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.CMD2DB_line.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.CMD2DB_line.setFont(font)
        self.CMD2DB_line.setText("")
        self.CMD2DB_line.setAlignment(QtCore.Qt.AlignCenter)
        self.CMD2DB_line.setObjectName("CMD2DB_line")
        self.CMD2DB_List = QtWidgets.QListWidget(self.CMD2DB)
        self.CMD2DB_List.setGeometry(QtCore.QRect(30, 170, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CMD2DB_List.setFont(font)
        self.CMD2DB_List.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.CMD2DB_List.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.CMD2DB_List.setObjectName("CMD2DB_List")
        self.CMD2DB_is2Ind = QtWidgets.QCheckBox(self.CMD2DB)
        self.CMD2DB_is2Ind.setGeometry(QtCore.QRect(30, 125, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.CMD2DB_is2Ind.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.CMD2DB_is2Ind.setFont(font)
        self.CMD2DB_is2Ind.setObjectName("CMD2DB_is2Ind")
        self.CMD2DB_dlm = QtWidgets.QLineEdit(self.CMD2DB)
        self.CMD2DB_dlm.setGeometry(QtCore.QRect(263, 126, 21, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.CMD2DB_dlm.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        self.CMD2DB_dlm.setFont(font)
        self.CMD2DB_dlm.setText("")
        self.CMD2DB_dlm.setMaxLength(1)
        self.CMD2DB_dlm.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.CMD2DB_dlm.setObjectName("CMD2DB_dlm")
        self.label = QtWidgets.QLabel(self.CMD2DB)
        self.label.setGeometry(QtCore.QRect(205, 128, 54, 12))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CMD2DB_info = QtWidgets.QLabel(self.CMD2DB)
        self.CMD2DB_info.setGeometry(QtCore.QRect(31, 150, 251, 16))
        self.CMD2DB_info.setStyleSheet("color: rgb(255, 255, 255);")
        self.CMD2DB_info.setText("")
        self.CMD2DB_info.setAlignment(QtCore.Qt.AlignCenter)
        self.CMD2DB_info.setObjectName("CMD2DB_info")
        self.CMD2DB_DRAG.raise_()
        self.CMD2DB_B.raise_()
        self.CMD2DB_VIEW.raise_()
        self.CMD2DB_line.raise_()
        self.CMD2DB_OK.raise_()
        self.CMD2DB_NO.raise_()
        self.CMD2DB_List.raise_()
        self.CMD2DB_is2Ind.raise_()
        self.CMD2DB_dlm.raise_()
        self.label.raise_()
        self.CMD2DB_info.raise_()
        self.CMD.raise_()
        self.CMD2DB.raise_()
        self.Q_comm.raise_()
        self.widget_2.raise_()
        self.frame_2.raise_()
        self.DEBUG_Pages.addTab(self.TAB_terminal, "")
        self.TAB_canvas = QtWidgets.QWidget()
        self.TAB_canvas.setObjectName("TAB_canvas")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.TAB_canvas)
        self.openGLWidget.setGeometry(QtCore.QRect(0, 0, 1074, 716))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 235, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.openGLWidget.setPalette(palette)
        self.openGLWidget.setObjectName("openGLWidget")
        self.frame_3 = QtWidgets.QFrame(self.TAB_canvas)
        self.frame_3.setGeometry(QtCore.QRect(0, 664, 1074, 48))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(125, 125, 160, 255));")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.DEBUG_Pages.addTab(self.TAB_canvas, "")
        self.Work_Area.addTab(self.TAB_Debug, "")
        self.TAB_Cluster = QtWidgets.QWidget()
        self.TAB_Cluster.setObjectName("TAB_Cluster")
        self.widget = QtWidgets.QWidget(self.TAB_Cluster)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1076, 740))
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 80, 738))
        self.widget_3.setStyleSheet("border-image: url(:/Res/Cluster_L.jpg);")
        self.widget_3.setObjectName("widget_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(8, 16, 64, 80))
        self.pushButton.setStyleSheet("border-image: url(:/Res/C_Btn_C.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(8, 120, 64, 80))
        self.pushButton_2.setStyleSheet("border-image: url(:/Res/C_Btn_M.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setGeometry(QtCore.QRect(8, 640, 64, 80))
        self.pushButton_3.setStyleSheet("border-image: url(:/Res/C_Btn_R.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(80, 0, 994, 738))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 975, 719))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.openGLWidget_2 = QtWidgets.QOpenGLWidget(self.scrollAreaWidgetContents)
        self.openGLWidget_2.setGeometry(QtCore.QRect(0, 0, 1280, 1280))
        self.openGLWidget_2.setObjectName("openGLWidget_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.widget_3.raise_()
        self.Work_Area.addTab(self.TAB_Cluster, "")
        self.TAB_Table = QtWidgets.QWidget()
        self.TAB_Table.setObjectName("TAB_Table")
        self.DB_list = QtWidgets.QListWidget(self.TAB_Table)
        self.DB_list.setGeometry(QtCore.QRect(0, 0, 171, 741))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 235, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.DB_list.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DB_list.setFont(font)
        self.DB_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.DB_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.DB_list.setObjectName("DB_list")
        item = QtWidgets.QListWidgetItem()
        self.DB_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.DB_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.DB_list.addItem(item)
        self.DB_toolbar = QtWidgets.QWidget(self.TAB_Table)
        self.DB_toolbar.setGeometry(QtCore.QRect(171, 703, 904, 32))
        self.DB_toolbar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(125, 125, 160, 255));")
        self.DB_toolbar.setObjectName("DB_toolbar")
        self.DB_save = QtWidgets.QPushButton(self.DB_toolbar)
        self.DB_save.setGeometry(QtCore.QRect(851, 0, 32, 32))
        self.DB_save.setStyleSheet("border-image: url(:/Res/DB_save.png);")
        self.DB_save.setText("")
        self.DB_save.setObjectName("DB_save")
        self.DB_paint = QtWidgets.QPushButton(self.DB_toolbar)
        self.DB_paint.setGeometry(QtCore.QRect(40, 0, 32, 32))
        self.DB_paint.setStyleSheet("border-image: url(:/Res/DB_paint.png);")
        self.DB_paint.setText("")
        self.DB_paint.setObjectName("DB_paint")
        self.DB_load = QtWidgets.QPushButton(self.DB_toolbar)
        self.DB_load.setGeometry(QtCore.QRect(800, 0, 32, 32))
        self.DB_load.setStyleSheet("border-image: url(:/Res/DB_load.png);")
        self.DB_load.setText("")
        self.DB_load.setObjectName("DB_load")
        self.DB_table = QtWidgets.QTableWidget(self.TAB_Table)
        self.DB_table.setGeometry(QtCore.QRect(171, 0, 904, 706))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(13, 13, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 13, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 13, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.DB_table.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.DB_table.setFont(font)
        self.DB_table.setObjectName("DB_table")
        self.DB_table.setColumnCount(1)
        self.DB_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.DB_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.DB_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(22, 22, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.DB_table.setItem(0, 0, item)
        self.DB_table.raise_()
        self.DB_list.raise_()
        self.DB_toolbar.raise_()
        self.Work_Area.addTab(self.TAB_Table, "")
        self.Status = QtWidgets.QFrame(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(0, 760, 1080, 40))
        self.Status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Status.setObjectName("Status")
        self.Clock_Text = QtWidgets.QLabel(self.Status)
        self.Clock_Text.setGeometry(QtCore.QRect(823, 10, 251, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 255, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 255, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 245, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 255, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Clock_Text.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setBold(True)
        font.setWeight(75)
        self.Clock_Text.setFont(font)
        self.Clock_Text.setAlignment(QtCore.Qt.AlignCenter)
        self.Clock_Text.setObjectName("Clock_Text")
        self.Status_Back = QtWidgets.QLabel(self.Status)
        self.Status_Back.setGeometry(QtCore.QRect(0, 0, 1080, 40))
        self.Status_Back.setStyleSheet("border-image: url(:/Res/Status.jpg);")
        self.Status_Back.setText("")
        self.Status_Back.setObjectName("Status_Back")
        self.Menu_Btn = QtWidgets.QPushButton(self.Status)
        self.Menu_Btn.setGeometry(QtCore.QRect(9, 4, 32, 32))
        self.Menu_Btn.setStyleSheet("border-image: url(:/Res/logo2.png);")
        self.Menu_Btn.setText("")
        self.Menu_Btn.setObjectName("Menu_Btn")
        self.MenuBtn_CMD = QtWidgets.QPushButton(self.Status)
        self.MenuBtn_CMD.setGeometry(QtCore.QRect(82, 6, 32, 32))
        self.MenuBtn_CMD.setStyleSheet("border-image: url(:/Res/Menu_Btn_T.png);")
        self.MenuBtn_CMD.setText("")
        self.MenuBtn_CMD.setObjectName("MenuBtn_CMD")
        self.Status_Back.raise_()
        self.Clock_Text.raise_()
        self.Menu_Btn.raise_()
        self.MenuBtn_CMD.raise_()
        self.LOGIN = QtWidgets.QFrame(self.centralwidget)
        self.LOGIN.setGeometry(QtCore.QRect(0, 1000, 1080, 762))
        self.LOGIN.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LOGIN.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LOGIN.setObjectName("LOGIN")
        self.Login_B = QtWidgets.QLabel(self.LOGIN)
        self.Login_B.setGeometry(QtCore.QRect(0, 0, 1080, 764))
        self.Login_B.setStyleSheet("border-image: url(:/Res/Login_back.jpg);")
        self.Login_B.setObjectName("Login_B")
        self.label_2 = QtWidgets.QLabel(self.LOGIN)
        self.label_2.setGeometry(QtCore.QRect(310, 260, 450, 265))
        self.label_2.setStyleSheet("border-image: url(:/Res/Login.png);")
        self.label_2.setObjectName("label_2")
        self.List_IP = QtWidgets.QListWidget(self.LOGIN)
        self.List_IP.setGeometry(QtCore.QRect(0, 484, 231, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.List_IP.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.List_IP.setFont(font)
        self.List_IP.setObjectName("List_IP")
        self.Btn_login = QtWidgets.QPushButton(self.LOGIN)
        self.Btn_login.setGeometry(QtCore.QRect(492, 458, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_login.setFont(font)
        self.Btn_login.setStyleSheet("border-image: url(:/Res/Login_Btn.png);")
        self.Btn_login.setObjectName("Btn_login")
        self.Text_loginwarn = QtWidgets.QLabel(self.LOGIN)
        self.Text_loginwarn.setGeometry(QtCore.QRect(382, 493, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Text_loginwarn.setFont(font)
        self.Text_loginwarn.setAlignment(QtCore.Qt.AlignCenter)
        self.Text_loginwarn.setObjectName("Text_loginwarn")
        self.label_4 = QtWidgets.QLabel(self.LOGIN)
        self.label_4.setGeometry(QtCore.QRect(0, 450, 128, 36))
        self.label_4.setObjectName("label_4")
        self.TextEdit_UserID = QtWidgets.QLineEdit(self.LOGIN)
        self.TextEdit_UserID.setGeometry(QtCore.QRect(434, 320, 260, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.TextEdit_UserID.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.TextEdit_UserID.setFont(font)
        self.TextEdit_UserID.setAlignment(QtCore.Qt.AlignCenter)
        self.TextEdit_UserID.setObjectName("TextEdit_UserID")
        self.TextEdit_PWD = QtWidgets.QLineEdit(self.LOGIN)
        self.TextEdit_PWD.setGeometry(QtCore.QRect(433, 415, 260, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.TextEdit_PWD.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(11)
        self.TextEdit_PWD.setFont(font)
        self.TextEdit_PWD.setAlignment(QtCore.Qt.AlignCenter)
        self.TextEdit_PWD.setObjectName("TextEdit_PWD")
        self.TextEdit_HostID = QtWidgets.QLineEdit(self.LOGIN)
        self.TextEdit_HostID.setGeometry(QtCore.QRect(434, 357, 260, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.TextEdit_HostID.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(11)
        self.TextEdit_HostID.setFont(font)
        self.TextEdit_HostID.setAlignment(QtCore.Qt.AlignCenter)
        self.TextEdit_HostID.setObjectName("TextEdit_HostID")
        self.Check_AddIP = QtWidgets.QCheckBox(self.LOGIN)
        self.Check_AddIP.setGeometry(QtCore.QRect(620, 452, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Check_AddIP.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Check_AddIP.setFont(font)
        self.Check_AddIP.setObjectName("Check_AddIP")
        self.Check_Savepwd = QtWidgets.QCheckBox(self.LOGIN)
        self.Check_Savepwd.setGeometry(QtCore.QRect(620, 470, 121, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Check_Savepwd.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Check_Savepwd.setFont(font)
        self.Check_Savepwd.setObjectName("Check_Savepwd")
        self.Main_Menu = QtWidgets.QWidget(self.centralwidget)
        self.Main_Menu.setGeometry(QtCore.QRect(0, 1000, 340, 312))
        self.Main_Menu.setObjectName("Main_Menu")
        self.listWidget = QtWidgets.QListWidget(self.Main_Menu)
        self.listWidget.setGeometry(QtCore.QRect(7, 5, 191, 300))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setIconSize(QtCore.QSize(12, 12))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.Menu_B = QtWidgets.QLabel(self.Main_Menu)
        self.Menu_B.setGeometry(QtCore.QRect(0, 0, 312, 312))
        self.Menu_B.setStyleSheet("border-image: url(:/Res/Menu_B.png);")
        self.Menu_B.setText("")
        self.Menu_B.setObjectName("Menu_B")
        self.Menu_B.raise_()
        self.listWidget.raise_()
        MainWnd.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWnd)
        self.Work_Area.setCurrentIndex(0)
        self.DEBUG_Pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWnd)

    def retranslateUi(self, MainWnd):
        _translate = QtCore.QCoreApplication.translate
        MainWnd.setWindowTitle(_translate("MainWnd", "Cluster Net (Ver 0.01)"))
        self.CMD_Clear.setToolTip(_translate("MainWnd", "Clear the Terminal"))
        self.CMD_Stop.setToolTip(_translate("MainWnd", "Send Crrl+C to the current running shell"))
        self.CMD_Add.setToolTip(_translate("MainWnd", "Send Crrl+C to the current running shell"))
        self.CMD2DB_is2Ind.setText(_translate("MainWnd", "first column as indices"))
        self.label.setText(_translate("MainWnd", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Delimiter</span></p></body></html>"))
        self.DEBUG_Pages.setTabText(self.DEBUG_Pages.indexOf(self.TAB_terminal), _translate("MainWnd", "TERMINAL"))
        self.DEBUG_Pages.setTabText(self.DEBUG_Pages.indexOf(self.TAB_canvas), _translate("MainWnd", "CANVAS"))
        self.Work_Area.setTabText(self.Work_Area.indexOf(self.TAB_Debug), _translate("MainWnd", "DEBUG"))
        self.Work_Area.setTabText(self.Work_Area.indexOf(self.TAB_Cluster), _translate("MainWnd", "CLUSTER"))
        __sortingEnabled = self.DB_list.isSortingEnabled()
        self.DB_list.setSortingEnabled(False)
        item = self.DB_list.item(0)
        item.setText(_translate("MainWnd", "<empty list>"))
        item = self.DB_list.item(1)
        item.setText(_translate("MainWnd", "t1"))
        item = self.DB_list.item(2)
        item.setText(_translate("MainWnd", "t2"))
        self.DB_list.setSortingEnabled(__sortingEnabled)
        self.DB_save.setToolTip(_translate("MainWnd", "Save Table"))
        self.DB_paint.setToolTip(_translate("MainWnd", "Paint in [Cluster]"))
        self.DB_load.setToolTip(_translate("MainWnd", "Load Table"))
        item = self.DB_table.verticalHeaderItem(0)
        item.setText(_translate("MainWnd", "<Empty>"))
        item = self.DB_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWnd", "<Empty>"))
        __sortingEnabled = self.DB_table.isSortingEnabled()
        self.DB_table.setSortingEnabled(False)
        item = self.DB_table.item(0, 0)
        item.setText(_translate("MainWnd", "<null>"))
        self.DB_table.setSortingEnabled(__sortingEnabled)
        self.Work_Area.setTabText(self.Work_Area.indexOf(self.TAB_Table), _translate("MainWnd", "TABLES"))
        self.Clock_Text.setText(_translate("MainWnd", "<Clock Error>"))
        self.Menu_Btn.setShortcut(_translate("MainWnd", "Esc"))
        self.MenuBtn_CMD.setShortcut(_translate("MainWnd", "Esc"))
        self.Text_loginwarn.setText(_translate("MainWnd", "<html><head/><body><p><span style=\" color:#ffffff;\">Waiting for Login...</span></p></body></html>"))
        self.label_4.setText(_translate("MainWnd", "<html><head/><body><p><img src=\":/Res/ListIP.png\"/></p></body></html>"))
        self.Check_AddIP.setText(_translate("MainWnd", "save info"))
        self.Check_Savepwd.setText(_translate("MainWnd", "save password"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWnd", "Connection Info"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

import UI_Res_Button_rc
import UI_Res_Frame_rc
